stages:
  - test

jobs:
- name: ruby
  stage: test
  image: ruby:2.7.2
  services:
  - name: db
    image: postgres
    environment:
    - POSTGRES_DB=sample_rails_app_db_test
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=secrets
  script:
  - bundle install --without production --path vendor/bundle
  - rails db:migrate
  - rails test
  cache:
    - key: bundle
      paths:
        - vendor/bundle
